### ISSUE TITLE
Discussion about  structure of the B0 tutorial notebook

### ISSUE THREAD

**Issue by behrouzvia** [neuropoly/realtime-dynamic-shimming#12]
I have modified the notebook to use a phase dataset under NeuroPoly's google drive which is accessible to the team members.  Eventually, after it's done, we can upload them to a public repository. I am eager to receive your feedback on improving this notebook.

**Comment by evaalonsoortiz** [comment]
@behrouzvia https://github.com/neuropoly/realtime-dynamic-shimming is a repository for a project titled "Dynamic Shimming in the Cervical Spinal Cord for Multi-Echo Gradient-Echo Imaging at 3 T". 

Your own project should be saved in its own repository, with the data and set to private.

I have removed your edits to restore the repository to its original form. Generally, when you have changes to propose to an existing repository, you must (1) open an issue describing the problem that needs to be addressed, (2) open a new branch and make changes in your branch, (3) open a pull request so that someone can revise your work, discuss and merge your branch will the main branch. 

I'm not sure why you were able to directly push to main, this should not have been the case.
